### PR TITLE
Feature: send back subscribe

### PR DESCRIPTION
**Pull request by yoongsiang2**

### CODE REVIEW

**Comment by yoongsiang2** [comment]
Snapshot of new printing:
image

**Comment by yoongsiang2** [comment]
Client able to receive data from Proxy:
image

**Comment by yoongsiang2** [comment]
WIP: need separate common subcrib msg to proxy and client.

**Comment by yoongsiang2** [comment]
image

**Review by AzuraTarmiziIntel — APPROVED** [review]
LGTM

**Pull request merged**
